### ISSUE TITLE
Problem with Mordred Docker Container

### ISSUE THREAD

**Issue by BenLloydPearson** [Bitergia/mordred#18]
Hello,

I tried to follow the instructions found at mordred/docker/readme.md; I followed everything exactly, but only switched the git repos I'm tracking in projects.json.

All of the containers launch successfully, but after about 5 minutes the mordred container crashes and it crashes again immediately if I try to start it with docker-compose. I checked the docker logs and found this at the end:

`/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'namespaces'
  warnings.warn(msg)
/home/bitergia/stage: line 79: bin/mordred: No such file or directory`

It seems the bin/mordred executable is, in fact, missing.

Here is my docker-compose.yml config:

mordred:
  image: bitergia/mordred:latest
  volumes:
    - devel/mordred/docker/conf/:/home/bitergia/conf/
    - devel/logs/:/home/bitergia/logs/
  links:
    - mariadb
    - elasticsearch

mariadb:
  restart: "always"
  image: mariadb:10.0
  expose:
    - "3306"
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes

elasticsearch:
  restart: "always"
  image: elasticsearch:2.2
  command: elasticsearch -Des.network.bind_host=0.0.0.0 -Dhttp.max_content_length=2000mb
  ports:
    - "9200:9200"

kibana:
  image: bitergia/kibiter:4.4.1
  environment:
    - PROJECT_NAME=mytest
    - NODE_OPTIONS=--max-old-space-size=200
  links:
    - elasticsearch
  ports:
    - "8081:5601"

kibana-ro:
  image: bitergia/kibiter:4.4.1-public
  environment:
    - PROJECT_NAME=mytest
    - NODE_OPTIONS=--max-old-space-size=200
  links:
    - elasticsearch
  ports:
    - "8091:5601"

**Comment by BenLloydPearson** [comment]
Here's some debugging I did.

I added the following line to the volumes: portion of the mordred section in docker-compose.yml

`-devel/mordred/:/home/bitergia/mordred/`

devel/mordred on the host machine contains a clone of the mordred git repo.

This seems to have taken care of the error I saw before, however, I now receive the following error after mordred handles all of the entries in orgs_file.json:

`Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "./mordred/task_manager.py", line 87, in run
    task.run()
  File "./mordred/task_panels.py", line 283, in run
    menu = self.__get_dash_menu()
  File "./mordred/task_panels.py", line 268, in __get_dash_menu
    ds_menu = self.__get_menu_entries()
  File "./mordred/task_panels.py", line 242, in __get_menu_entries
    dash_name = get_dashboard_name(subentry['panel'])
  File "./grimoire_elk/panels.py", line 333, in get_dashboard_name
    with open(import_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'panels/dashboards/github_issues_timing-organizations.json'
`

Once again, github_issues_timing-organizations.json is missing from the docker container.

**Comment by BenLloydPearson** [comment]
I did some more digging.

It seems my original problem was a result of me using the bitergia/morded:latest docker image, when I needed to use bitergia/morded:catwoman to match what was configured in requirements.json. The Mordred tutorial should probably be updated to indicate these values need to match.

The error I identified in my previous comment seems to be a separate error that I'm still seeing. However, I have commits that have now been imported to elasticsearch, I just don't have any metadashboards in Kibana. This isn't too big of an issue for me because I'll be using my own dashboards, but it might warrant more investigation anyways.

**Comment by sanacl** [comment]
Hi @BenLloydPearson, you are right. The latest docker image is not compatible with previous versions. We are discussing whether we should take care of this or not so in the meantime I recommend you to use the latest version available at https://github.com/Bitergia/mordred/tree/master/docker/unified_releases with the latest docker image.

I'm updating the documentation asap. 

Thank you for your contribution :+1:

**Comment by sanacl** [comment]
@BenLloydPearson I've just include a couple of notes in the doc as you suggested. https://github.com/Bitergia/mordred/commit/6fb47117fb75562d71cbcb3babdfb718a69b3c8e

I'm closing the issue now. Please reopen if you think it is not clear enough.
